/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit_freak;

/**
 *
 * @author Asus
 */
public class DietPlanMuscle extends javax.swing.JFrame {

    /**
     * Creates new form DietPlanMuscle
     */
    public DietPlanMuscle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Diet Plan for Muscle and Strength Gain");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("We will consume 200 to 400 calories more than required in a day \ni.e. we will be following calorific surplus diet\n\n\nMeal 1: Wake-Up Meal/Pre-Breakfast\nVegetarians: Whey Protein Shake and One medium to large size piece of fruit (preferably bananas or grapes)\nNon-Vegetarians: Whey Protein Shake and One medium to large size piece of fruit (preferably bananas or grapes)\n\nMeal 2: Breakfast\nNutrient Groups: Protein + Low GI carbs or Slow Digesting Carbs + Healthy Fats\nWhat to Eat:\nVegetarians: Paneer Parantha (3 medium pieces)/Paneer Bhurji + Greek Yogurt/ Low-fat yogurt + sprout salad (1 medium bowl)\nNon-Vegetarians: Eggs, Oatmeal, Milk, and Nuts\n\nMeal 3: Mid-Morning Meal/Snacks\nNutrient Groups: Protein + Slow acting carbs + Veggies\nWhat to Eat:\nVegetarians: Roasted chickpeas (1 medium bowl) + Small size fruit (1 medium size) + mixed vegetables salad\nNon-Vegetarians: Brown Rice, Chicken, and Broccoli\n\nMeal 4: Lunch\nNutrient Groups: Protein + Slow acting carbs + Veggies\nWhat to eat:\nVegetarians: Mixed bean sabzi + Brown Rice (1 medium cup) + Broccoli/Cauliflower (1 cup cooked)\nNon-Vegetarians: Fish, Brown Rice, Mixed Veggies\n\nMeal 5: Mid-Afternoon/Pre-Workout Meal\nNutrient Groups: Protein + Low GI carbs\nWhat to eat:\nVegetarians: Whole grain toast (spread almond butter or avocado) + Baked sweet potatoes (1 small bowl)\nNon-Vegetarians: Sweet potato and Protein powder\n\n\nWe also have to take post workout and preworkout meal \nPre workout meal -food and supplement that provides power example banana,bcaa , creatine.\nPost workout -should contain contain fast protein for fast muscle recovery example- whey protein ,boiled eggs.\n(If you get bored of same meal everyday then change some flavours and spices in vegetables and meat and change vegetables that is similar in nutrient content.) ");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DietPlanMuscle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DietPlanMuscle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DietPlanMuscle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DietPlanMuscle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DietPlanMuscle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
