/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit_freak;

/**
 *
 * @author Asus
 */
public class WorkoutPlanFatLoss extends javax.swing.JFrame {

    /**
     * Creates new form WorkoutPlanFatLoss
     */
    public WorkoutPlanFatLoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Workout plan for Fat Loss: ");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Monday: \nTotal-Body Strength Training \n1.Bodyweight Squats—15 reps. \nQuick tip: Get low, keep your chest up, and don't let your knees go over your toes during this lower-body move. \n\n2.Dumbbell Bench Press—12 reps. \nQuick tip: Position yourself so your head, back, and butt are all on the bench, your feet flat on the floor. \n\n3.Dumbbell Row—12 reps each side. \nQuick tip: If you don't have a bench available, try a bent-over row. \n\n4.Lying Isometric Y—Hold for 30 seconds. \nQuick tip: You can keep your legs on the ground for this one if that feels more comfortable. \n\n5.Box Step-Ups—15 reps each leg. \nQuick tip: Alternate between your left and right leg, and for an extra challenge, step your lifted foot into a lunge as you come down from the box. \n\n6.Plank—Hold for 30 seconds. Quick tip: Make sure you're keeping your core tight! Do the circuit 3x, resting for 1 minute between each round.  \n\nTuesday: \nSprint Intervals 30 seconds: \nFull-out sprint 60 seconds: \nModerate pace jog Do this 12x (many of you think jogging way too long at slow pace will decrease weight yes that is partially true but by running far distances only muscle mass gets reduced not the fat) \n\nWednesday: \nFoam Rolling + 12,000 Steps \nIt is a recovery day but we don't have to fully rest. \n\nThursday: \nTotal-Body Strength Training \nDo the same workout you did on Monday.  \n\nFriday: \nHigh-Intensity Group Fitness \nTake part in a intense group activity ,like-cycling ,trekking, playing  outdoor sports. \n\nSaturday: \nTotal-Body Strength Training Do the same workout you did on Monday and Thursday. \n\nSunday: \nRest Day Enjoy your rest day. Have fun. \n(Follow this routine for 1 month after that when you are familiar with training increase no. Of reps and sets gradually).");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlanFatLoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlanFatLoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlanFatLoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlanFatLoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkoutPlanFatLoss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
